version: '3.0'

services:
  grafana:
    container_name: 'targetenergy-grafanatable-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/targetenergy-grafanatable-panel
      - ./provisioning:/etc/grafana/provisioning
      - ..:/root/targetenergy-grafanatable-panel
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: targetenergy-grafanatable-panel
